### PR TITLE
add outcome, reason, partial and billable to response vars

### PR DESCRIPTION
**Pull request by zalary**
suspect this might solve the problem on staging where some event information is not being set as expected

### CODE REVIEW

**Comment by alexkwolfe** [comment]
I don't understand how this change affects the data appended.

**Comment by zalary** [comment]
it didn't actually change the appended data, but these data points were not getting populated correctly because they were not available in the response vars.   so outcome was always defaulting to `success` per the [handler](https://github.com/activeprospect/leadconduit-handler/blob/master/src/middleware/integrate.coffee#L36-L42) because there was no outcome being set on the integration.  the billable and partial flags also weren't getting set.

**Comment by alexkwolfe** [comment]
Hmm. As far as I'm aware the handler does not rely on the presence or absence of request variables while appending data. IMO, there is or was something else going on here. The code you linked relates to how the handler responds to the source.

**Comment by zalary** [comment]
if you have any ideas as to what might be going on, please let me know.   I talked this over with @cgrayson last night and he suggested that the missing outcome/reason/partial/billable from the response variables might be the issues.  You can see the same request from last night in that same account - and the response before adding these vars was a `success` with no partial or billable flags.

https://next.staging.leadconduit.com/events/54da915c19942fe839490dc1?event_id=54da915c19942fe839490dc2

**Comment by cgrayson** [comment]
Sorry, that link to the wrong part of the handler was my fault. Perhaps [this one](https://github.com/activeprospect/leadconduit-handler/blob/master/src/steps/recipient-step.coffee#L180) is more germane. 

We witnessed this integration incorrectly setting `outcome` and `reason`. Adding them to the `response.variables` fixed it.

**Comment by cgrayson** [comment]
After further sleuthing, it seems that the problem must have been the handler running old code, after all. :confounded: We still want `outcome` and `reason` listed in response variables, of course, but their absence wasn't the cause of the problem. :rat:s

**Comment by alexkwolfe** [comment]
One thing to keep in mind when dealing with response variables is that the order in which they are declared in an integration is the order they are displayed in the rule builder. 

So the most likely things that the user might want to decision on should go at the top of the list of response variables. 

In this case, I would probably move billable and partial down (and maybe reason?)

**Pull request merged**
